ALTER TABLE rides ADD COLUMN IF NOT EXISTS start_lat DOUBLE PRECISION;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS start_lon DOUBLE PRECISION;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS weather_city TEXT;
